In [1]:
import numpy as np

np.array([1, 2, 3, 4, 5])
type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [2]:
np.zeros(10, dtype=int)

#10 tane 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.random.randint(0, 10, size=10)

#hangi sınırlar arası ve kaç tane int istiyorsun

array([8, 8, 3, 7, 2, 6, 7, 4, 9, 0])

In [6]:
np.random.normal(10, 4, (3, 4))

#ort = 10 , stand. sapma = 4 ve (3,4)lük bir array oluştur

array([[ 7.81027169,  7.40315666,  2.73859072,  9.06100375],
       [ 5.98723998, 12.99152384,  8.14438861,  8.48145987],
       [ 9.48586742, 17.51681577,  9.69230237,  2.80974497]])

In [9]:
a = np.random.randint(10, size=5)

a

#0'dan 10'a kadar 5 tane random sayı

array([7, 6, 6, 7, 5])

In [11]:
a.ndim #boyut sayısı bilgisi

1

In [12]:
a.shape #boyut bilgisi

(5,)

In [13]:
a.size #toplam eleman sayısı

5

In [14]:
a.dtype #tip bilgisi

dtype('int32')

In [20]:
#reshaping

ar = np.random.randint(1, 10, size=9)

ar

array([6, 9, 5, 3, 9, 4, 9, 4, 9])

In [22]:
ar.reshape(3, 3)

#üstteki arrayi 3e 3lük yaptık (burda eleman sayılarına dikkat)

array([[6, 9, 5],
       [3, 9, 4],
       [9, 4, 9]])

In [23]:
#index seçimleri

a = np.random.randint(10, size=10)

a

array([0, 5, 4, 7, 7, 5, 9, 9, 5, 1])

In [24]:
a[0]

0

In [25]:
a[0:5] #slicing

array([0, 5, 4, 7, 7])

In [26]:
a[0] = 999 #0. index değişti

a

array([999,   5,   4,   7,   7,   5,   9,   9,   5,   1])

In [28]:
m = np.random.randint(10, size=(3, 5)) 

m

#0'dan 10'a kadar , boyut bilgisi (3,5)

array([[6, 0, 4, 0, 0],
       [8, 3, 9, 7, 1],
       [2, 8, 4, 6, 8]])

In [29]:
m[0, 0]

6

In [30]:
m[2, 3]

6

In [31]:
m[2, 3] = 2.9

In [33]:
#2yi aldı

m

array([[6, 0, 4, 0, 0],
       [8, 3, 9, 7, 1],
       [2, 8, 4, 2, 8]])

In [35]:
m[:, 0] #tüm satıları seç ve 0.sütunu seç

array([6, 8, 2])

In [36]:
m[1, :] #1. satırı seç ve tüm sütunları seç

array([8, 3, 9, 7, 1])

In [37]:
m[0:2, 0:3] #satırlardan 0dan 2ye kadar sütunlarda 0dan 3e kadar

array([[6, 0, 4],
       [8, 3, 9]])

In [38]:
#fancy index

v = np.arange(0, 30, 3) #0dan 30a kadar 3er 3er array oluştur
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
catch = [1, 2, 3]

In [41]:
v[catch] #1. index 2.index 3.index gelir

array([3, 6, 9])

In [42]:
#koşullu işlemler

v = np.array([1, 2, 3, 4, 5])

In [47]:
#döngüler ile listenin 3ten küçük elemanlarını yakalama

new = []

for eleman in v:
    if eleman < 3:
        new.append(eleman)
        
new        

[1, 2]

In [49]:
#aynı işlem numpy ile

v < 3  #numpy özelliği

array([ True,  True, False, False, False])

In [50]:
v[v < 3]

array([1, 2])

In [51]:
#matematiksel işlemler

v = np.array([1, 2, 3, 4, 5])

v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [52]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [53]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [54]:
v - 1

array([0, 1, 2, 3, 4])

In [55]:
np.subtract(v, 1) #çıkarma

array([0, 1, 2, 3, 4])

In [56]:
np.add(v, 1) #toplama

array([2, 3, 4, 5, 6])

In [57]:
np.mean(v) #ortalama

3.0

In [58]:
np.sum(v) #tüm elemanları toplama

15

In [59]:
np.min(v)

1

In [60]:
np.max(v)

5

In [61]:
np.var(v) #varyans

2.0

In [63]:
#iki bilinmeyenli denklem çözümü

# 5*x0 + x1 = 12
# x0 + 3*x1 = 10


a = np.array([[5, 1], [1, 3]])
b = np.array([12, 10])

np.linalg.solve(a, b)

array([1.85714286, 2.71428571])